# This is a basic workflow to help you get started with Actions
name: Blob storage website CI (CRA-ARC)

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete contents of blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob delete-batch --account-name staticwebsitehostingcra --pattern * --auth-mode key --source .
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
